#!/bin/sh

# ------------------------------------------------------------
# Input
# ------------------------------------------------------------

# US keyboard + CapsLock -> Ctrl
riverctl keyboard-layout -options 'ctrl:nocaps' us

# Keyboard repeat
riverctl set-repeat 50 300


# ------------------------------------------------------------
# Applications
# ------------------------------------------------------------

# Terminal
riverctl map normal Super+Shift Return spawn foot

# Launcher
riverctl map normal Super D spawn 'bemenu-run'


# ------------------------------------------------------------
# Window management
# ------------------------------------------------------------

# Close focused window
riverctl map normal Super Q close

# Exit River
riverctl map normal Super+Shift E exit

# Focus next / previous
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Swap next / previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Focus next / previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Send window to next / previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Promote focused window to main
riverctl map normal Super Return zoom

# Main ratio
riverctl map normal Super H \
    send-layout-cmd rivertile 'main-ratio -0.05'

riverctl map normal Super L \
    send-layout-cmd rivertile 'main-ratio +0.05'

# Main window count
riverctl map normal Super+Shift H \
    send-layout-cmd rivertile 'main-count +1'

riverctl map normal Super+Shift L \
    send-layout-cmd rivertile 'main-count -1'

# Float
riverctl map normal Super Space toggle-float

# Fullscreen
riverctl map normal Super F toggle-fullscreen


# ------------------------------------------------------------
# Layout orientation
# ------------------------------------------------------------

riverctl map normal Super Up \
    send-layout-cmd rivertile 'main-location top'

riverctl map normal Super Right \
    send-layout-cmd rivertile 'main-location right'

riverctl map normal Super Down \
    send-layout-cmd rivertile 'main-location bottom'

riverctl map normal Super Left \
    send-layout-cmd rivertile 'main-location left'


# ------------------------------------------------------------
# Tags
# ------------------------------------------------------------

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))

    # Super+[1-9]
    riverctl map normal Super "$i" \
        set-focused-tags "$tags"

    # Super+Shift+[1-9]
    riverctl map normal Super+Shift "$i" \
        set-view-tags "$tags"

    # Super+Control+[1-9]
    riverctl map normal Super+Control "$i" \
        toggle-focused-tags "$tags"

    # Super+Shift+Control+[1-9]
    riverctl map normal Super+Shift+Control "$i" \
        toggle-view-tags "$tags"
done

all_tags=$(((1 << 32) - 1))

riverctl map normal Super 0 \
    set-focused-tags "$all_tags"

riverctl map normal Super+Shift 0 \
    set-view-tags "$all_tags"


# ------------------------------------------------------------
# Mouse
# ------------------------------------------------------------

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float


# ------------------------------------------------------------
# Media keys
# ------------------------------------------------------------

for mode in normal locked
do
    # Volume
    riverctl map "$mode" None XF86AudioRaiseVolume \
        spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'

    riverctl map "$mode" None XF86AudioLowerVolume \
        spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'

    riverctl map "$mode" None XF86AudioMute \
        spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Microphone
    riverctl map "$mode" None XF86AudioMicMute \
        spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'

    # Media playback
    riverctl map "$mode" None XF86AudioMedia \
        spawn 'playerctl play-pause'

    riverctl map "$mode" None XF86AudioPlay \
        spawn 'playerctl play-pause'

    riverctl map "$mode" None XF86AudioPrev \
        spawn 'playerctl previous'

    riverctl map "$mode" None XF86AudioNext \
        spawn 'playerctl next'

    # Brightness
    riverctl map "$mode" None XF86MonBrightnessUp \
        spawn 'brightnessctl set +5%'

    riverctl map "$mode" None XF86MonBrightnessDown \
        spawn 'brightnessctl set 5%-'
done


# ------------------------------------------------------------
# Screenshot
# ------------------------------------------------------------

riverctl map normal None Print \
    spawn "$HOME/.local/bin/screenshot-region"


# ------------------------------------------------------------
# Lock
# ------------------------------------------------------------

riverctl map normal Super+Shift X \
    spawn 'swaylock'


# ------------------------------------------------------------
# Reload config
# ------------------------------------------------------------

riverctl map normal Super R \
    spawn "$HOME/.local/bin/river-reload"


# ------------------------------------------------------------
# Appearance
# ------------------------------------------------------------

riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl set-cursor-warp on-focus-change
riverctl focus-follows-cursor normal

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

riverctl default-layout rivertile
